development:
    cloud_name:  "photo-app"
    api_key:  "435854513936713"
    api_secret:  "ift4DKmaDkfx87H1fcwWeVVW_C0"

production:
    cloud_name:  "photo-app"
    api_key:  "435854513936713"
    api_secret:  "ift4DKmaDkfx87H1fcwWeVVW_C0"
