development:
  cloud_name: photo-app
<<<<<<< HEAD
  api_key: '971867482615178'
  api_secret: uC84bs9Aw5aCJYK91CM_AzZnCYU
=======
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
>>>>>>> 3d4947dff191d24a5a7a16fb146c8d9216383edc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: photo-app
<<<<<<< HEAD
  api_key: '971867482615178'
  api_secret: uC84bs9Aw5aCJYK91CM_AzZnCYU
=======
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
>>>>>>> 3d4947dff191d24a5a7a16fb146c8d9216383edc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: photo-app
<<<<<<< HEAD
  api_key: '971867482615178'
  api_secret: uC84bs9Aw5aCJYK91CM_AzZnCYU
=======
  api_key: <%= ENV["cloud_key"] %>
  api_secret: <%= ENV["cloud_secret"] %>
>>>>>>> 3d4947dff191d24a5a7a16fb146c8d9216383edc
  enhance_image_tag: true
  static_image_support: false
