---
development:
  cloud_name: photo-app
  api_key: '442877671844546'
  api_secret: AFHZTZh7Jk_9ogV4tiyTcHcS7iE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: photo-app
  api_key: '442877671844546'
  api_secret: AFHZTZh7Jk_9ogV4tiyTcHcS7iE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: photo-app
  api_key: '442877671844546'
  api_secret: AFHZTZh7Jk_9ogV4tiyTcHcS7iE
  enhance_image_tag: true
  static_image_support: false
